# Generated by Django 5.1.6 on 2025-02-17 12:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='clienteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('celular', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='produtoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('imagem', models.ImageField(upload_to='uploads/product/')),
                ('desc', models.CharField(blank=True, default='', max_length=320, null=True)),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appLoja.categoriamodel')),
            ],
        ),
        migrations.CreateModel(
            name='pedidoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enderec', models.CharField(blank=True, default='', max_length=120)),
                ('data', models.DateField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=False)),
                ('quantidade', models.IntegerField(default=1)),
                ('celular', models.CharField(blank=True, default='', max_length=14)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appLoja.clientemodel')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appLoja.produtomodel')),
            ],
        ),
    ]
