# Generated by Django 5.1.6 on 2025-02-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appLoja', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categoriaModel',
            new_name='categoria',
        ),
        migrations.RenameModel(
            old_name='clienteModel',
            new_name='cliente',
        ),
        migrations.RenameModel(
            old_name='pedidoModel',
            new_name='pedido',
        ),
        migrations.RenameModel(
            old_name='produtoModel',
            new_name='produto',
        ),
    ]
