# Generated by Django 5.1.6 on 2025-02-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLoja', '0003_alter_produto_imagem_alter_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='desconto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='descontoPrec',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
