# Generated by Django 5.1.6 on 2025-02-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appLoja', '0004_produto_desconto_produto_descontoprec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'categorias'},
        ),
    ]
