# Generated by Django 4.2.20 on 2025-03-30 13:52

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appLoja', '0005_alter_categoria_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_modif', models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User)),
                ('celular', models.CharField(blank=True, max_length=14)),
                ('endec1', models.CharField(blank=True, max_length=200)),
                ('endec2', models.CharField(blank=True, max_length=200)),
                ('cidade', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(blank=True, max_length=200)),
                ('cod_postal', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
