# Generated by Django 4.2.20 on 2025-03-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLoja', '0006_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='persiste_carrinho',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
