# Generated by Django 4.2.20 on 2025-03-31 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appLoja', '0007_perfil_persiste_carrinho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfis'},
        ),
    ]
