# Generated by Django 4.2.20 on 2025-03-31 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPagamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endecevio',
            options={'verbose_name_plural': 'Endereços de Envio'},
        ),
    ]
