# Generated by Django 4.2.20 on 2025-03-31 20:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appPagamento', '0002_alter_endecevio_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EndecEvio',
            new_name='EndecEnvio',
        ),
    ]
