# Generated by Django 4.2.20 on 2025-04-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPagamento', '0003_rename_endecevio_endecenvio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endecenvio',
            old_name='cidade',
            new_name='envio_cidade',
        ),
        migrations.RenameField(
            model_name='endecenvio',
            old_name='cod_postal',
            new_name='envio_cod_postal',
        ),
        migrations.RenameField(
            model_name='endecenvio',
            old_name='email',
            new_name='envio_email',
        ),
        migrations.RenameField(
            model_name='endecenvio',
            old_name='endec1',
            new_name='envio_endec1',
        ),
        migrations.RenameField(
            model_name='endecenvio',
            old_name='endec2',
            new_name='envio_endec2',
        ),
        migrations.RenameField(
            model_name='endecenvio',
            old_name='estado',
            new_name='envio_estado',
        ),
        migrations.RenameField(
            model_name='endecenvio',
            old_name='nome_completo',
            new_name='envio_nome_completo',
        ),
    ]
