# Generated by Django 4.2.20 on 2025-04-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPagamento', '0004_rename_cidade_endecenvio_envio_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endecenvio',
            name='envio_cod_postal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='endecenvio',
            name='envio_estado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
