# Generated by Django 4.2.20 on 2025-04-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPagamento', '0005_alter_endecenvio_envio_cod_postal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endecenvio',
            name='envio_email',
        ),
    ]
