# Generated by Django 4.2.20 on 2025-04-02 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appPagamento', '0006_remove_endecenvio_envio_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endecenvio',
            old_name='envio_cidade',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='endecenvio',
            old_name='envio_cod_postal',
            new_name='cod_postal',
        ),
        migrations.RenameField(
            model_name='endecenvio',
            old_name='envio_endec1',
            new_name='endec1',
        ),
        migrations.RenameField(
            model_name='endecenvio',
            old_name='envio_estado',
            new_name='endec2',
        ),
        migrations.RenameField(
            model_name='endecenvio',
            old_name='envio_endec2',
            new_name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='endecenvio',
            name='envio_nome_completo',
        ),
        migrations.AddField(
            model_name='endecenvio',
            name='estado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('envio_endec', models.TextField(max_length=500)),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
